//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertiser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Advertiser()
        {
            this.AdInfoes = new HashSet<AdInfo>();
        }
    
        public int advertiserid { get; set; }
        public string advertisername { get; set; }
        public string password { get; set; }
        public string username { get; set; }
        public string type { get; set; }
        public double adbudget { get; set; }
        public Nullable<int> adminid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<bool> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdInfo> AdInfoes { get; set; }
        public virtual Admin Admin { get; set; }
        public virtual User User { get; set; }
    }
}
