//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int clientid { get; set; }
        public string clientname { get; set; }
        public string password { get; set; }
        public string username { get; set; }
        public string type { get; set; }
        public string clientemail { get; set; }
        public string mobilenumber { get; set; }
        public int employeeid { get; set; }
        public bool status { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
